
copyright "#{Time.now.year} Net Skip"

force(true) # Skip HTML report verification
#default_language("en-US")
#automatic_release(true)
skip_screenshots(false)
skip_binary_upload(true)
precheck_include_in_app_purchases(false)

